# Generated by Django 6.0.5 on 2026-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to exercise thumbnail', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(default='None', help_text='e.g., Biceps, Chest, Shoulders', max_length=50),
        ),
    ]
