# Generated by Django 6.0.5 on 2026-05-23 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_date_workout_created_at_alter_workout_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutitem',
            name='workout_day',
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='created_at',
        ),
        migrations.AddField(
            model_name='workout',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutitem',
            name='workout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='rest',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='sets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.routine'),
        ),
        migrations.DeleteModel(
            name='WorkoutDay',
        ),
    ]
